"""
Universe of Indian Stocks (NSE & BSE) across multiple sectors & market caps.
"""

STOCKS_UNIVERSE = [
    {
        "symbol": "RELIANCE",
        "name": "Reliance Industries Ltd",
        "sector": "Energy & Petrochemicals",
        "market_cap_category": "Large Cap",
        "nse_ticker": "RELIANCE.NS",
        "bse_ticker": "500325.BO",
        "base_price": 2980.50,
        "base_pe": 27.8,
        "base_market_cap_cr": 2016500,
        "base_52w_high": 3217.90,
        "base_52w_low": 2220.30,
        "dividend_yield": 0.35,
    },
    {
        "symbol": "TCS",
        "name": "Tata Consultancy Services Ltd",
        "sector": "Information Technology",
        "market_cap_category": "Large Cap",
        "nse_ticker": "TCS.NS",
        "bse_ticker": "532540.BO",
        "base_price": 4250.75,
        "base_pe": 31.4,
        "base_market_cap_cr": 1538000,
        "base_52w_high": 4585.00,
        "base_52w_low": 3313.00,
        "dividend_yield": 1.15,
    },
    {
        "symbol": "HDFCBANK",
        "name": "HDFC Bank Ltd",
        "sector": "Banking & Financials",
        "market_cap_category": "Large Cap",
        "nse_ticker": "HDFCBANK.NS",
        "bse_ticker": "500180.BO",
        "base_price": 1650.20,
        "base_pe": 18.9,
        "base_market_cap_cr": 1255000,
        "base_52w_high": 1794.00,
        "base_52w_low": 1363.55,
        "dividend_yield": 1.20,
    },
    {
        "symbol": "BHARTIARTL",
        "name": "Bharti Airtel Ltd",
        "sector": "Telecommunications",
        "market_cap_category": "Large Cap",
        "nse_ticker": "BHARTIARTL.NS",
        "bse_ticker": "532454.BO",
        "base_price": 1720.00,
        "base_pe": 72.5,
        "base_market_cap_cr": 975000,
        "base_52w_high": 1779.00,
        "base_52w_low": 905.00,
        "dividend_yield": 0.45,
    },
    {
        "symbol": "ICICIBANK",
        "name": "ICICI Bank Ltd",
        "sector": "Banking & Financials",
        "market_cap_category": "Large Cap",
        "nse_ticker": "ICICIBANK.NS",
        "bse_ticker": "532174.BO",
        "base_price": 1285.40,
        "base_pe": 18.2,
        "base_market_cap_cr": 902000,
        "base_52w_high": 1335.00,
        "base_52w_low": 912.00,
        "dividend_yield": 0.80,
    },
    {
        "symbol": "INFY",
        "name": "Infosys Ltd",
        "sector": "Information Technology",
        "market_cap_category": "Large Cap",
        "nse_ticker": "INFY.NS",
        "bse_ticker": "500209.BO",
        "base_price": 1895.10,
        "base_pe": 28.6,
        "base_market_cap_cr": 788000,
        "base_52w_high": 1991.45,
        "base_52w_low": 1358.35,
        "dividend_yield": 2.25,
    },
    {
        "symbol": "SBIN",
        "name": "State Bank of India",
        "sector": "Banking & Financials",
        "market_cap_category": "Large Cap",
        "nse_ticker": "SBIN.NS",
        "bse_ticker": "500112.BO",
        "base_price": 795.30,
        "base_pe": 10.8,
        "base_market_cap_cr": 709000,
        "base_52w_high": 912.00,
        "base_52w_low": 543.15,
        "dividend_yield": 1.70,
    },
    {
        "symbol": "HINDUNILVR",
        "name": "Hindustan Unilever Ltd",
        "sector": "Consumer Goods (FMCG)",
        "market_cap_category": "Large Cap",
        "nse_ticker": "HINDUNILVR.NS",
        "bse_ticker": "500696.BO",
        "base_price": 2820.00,
        "base_pe": 62.4,
        "base_market_cap_cr": 662000,
        "base_52w_high": 3034.50,
        "base_52w_low": 2172.05,
        "dividend_yield": 1.50,
    },
    {
        "symbol": "ITC",
        "name": "ITC Ltd",
        "sector": "Consumer Goods (FMCG)",
        "market_cap_category": "Large Cap",
        "nse_ticker": "ITC.NS",
        "bse_ticker": "500875.BO",
        "base_price": 505.40,
        "base_pe": 30.2,
        "base_market_cap_cr": 631000,
        "base_52w_high": 528.55,
        "base_52w_low": 399.30,
        "dividend_yield": 2.75,
    },
    {
        "symbol": "LT",
        "name": "Larsen & Toubro Ltd",
        "sector": "Infrastructure & Capital Goods",
        "market_cap_category": "Large Cap",
        "nse_ticker": "LT.NS",
        "bse_ticker": "500510.BO",
        "base_price": 3610.00,
        "base_pe": 36.1,
        "base_market_cap_cr": 496000,
        "base_52w_high": 3919.90,
        "base_52w_low": 2862.00,
        "dividend_yield": 0.95,
    },
    {
        "symbol": "BAJFINANCE",
        "name": "Bajaj Finance Ltd",
        "sector": "Banking & Financials",
        "market_cap_category": "Large Cap",
        "nse_ticker": "BAJFINANCE.NS",
        "bse_ticker": "500034.BO",
        "base_price": 7450.00,
        "base_pe": 30.5,
        "base_market_cap_cr": 460000,
        "base_52w_high": 8192.00,
        "base_52w_low": 6365.00,
        "dividend_yield": 0.50,
    },
    {
        "symbol": "TATAMOTORS",
        "name": "Tata Motors Passenger Vehicles Ltd",
        "sector": "Automobile",
        "market_cap_category": "Large Cap",
        "nse_ticker": "TMPV.NS",
        "bse_ticker": "TMPV.BO",
        "base_price": 280.95,
        "base_pe": 15.2,
        "base_market_cap_cr": 105000,
        "base_52w_high": 315.00,
        "base_52w_low": 240.00,
        "dividend_yield": 1.10,
    },
    {
        "symbol": "SUNPHARMA",
        "name": "Sun Pharmaceutical Industries Ltd",
        "sector": "Pharmaceuticals & Healthcare",
        "market_cap_category": "Large Cap",
        "nse_ticker": "SUNPHARMA.NS",
        "bse_ticker": "524715.BO",
        "base_price": 1910.00,
        "base_pe": 41.2,
        "base_market_cap_cr": 458000,
        "base_52w_high": 1960.00,
        "base_52w_low": 1098.00,
        "dividend_yield": 0.70,
    },
    {
        "symbol": "MARUTI",
        "name": "Maruti Suzuki India Ltd",
        "sector": "Automobile",
        "market_cap_category": "Large Cap",
        "nse_ticker": "MARUTI.NS",
        "bse_ticker": "532500.BO",
        "base_price": 13100.00,
        "base_pe": 28.5,
        "base_market_cap_cr": 411000,
        "base_52w_high": 13680.00,
        "base_52w_low": 9250.00,
        "dividend_yield": 0.95,
    },
    {
        "symbol": "AXISBANK",
        "name": "Axis Bank Ltd",
        "sector": "Banking & Financials",
        "market_cap_category": "Large Cap",
        "nse_ticker": "AXISBANK.NS",
        "bse_ticker": "532215.BO",
        "base_price": 1235.00,
        "base_pe": 13.9,
        "base_market_cap_cr": 382000,
        "base_52w_high": 1339.65,
        "base_52w_low": 921.75,
        "dividend_yield": 0.20,
    },
    {
        "symbol": "ONGC",
        "name": "Oil & Natural Gas Corp Ltd",
        "sector": "Energy & Petrochemicals",
        "market_cap_category": "Large Cap",
        "nse_ticker": "ONGC.NS",
        "bse_ticker": "500312.BO",
        "base_price": 294.00,
        "base_pe": 7.4,
        "base_market_cap_cr": 369000,
        "base_52w_high": 344.75,
        "base_52w_low": 178.60,
        "dividend_yield": 4.10,
    },
    {
        "symbol": "NTPC",
        "name": "NTPC Ltd",
        "sector": "Energy & Power",
        "market_cap_category": "Large Cap",
        "nse_ticker": "NTPC.NS",
        "bse_ticker": "532555.BO",
        "base_price": 435.50,
        "base_pe": 19.8,
        "base_market_cap_cr": 422000,
        "base_52w_high": 448.45,
        "base_52w_low": 230.15,
        "dividend_yield": 1.75,
    },
    {
        "symbol": "TATASTEEL",
        "name": "Tata Steel Ltd",
        "sector": "Metals & Mining",
        "market_cap_category": "Large Cap",
        "nse_ticker": "TATASTEEL.NS",
        "bse_ticker": "500470.BO",
        "base_price": 164.20,
        "base_pe": 38.5,
        "base_market_cap_cr": 204000,
        "base_52w_high": 184.60,
        "base_52w_low": 114.25,
        "dividend_yield": 2.20,
    },
    {
        "symbol": "TITAN",
        "name": "Titan Company Ltd",
        "sector": "Consumer Goods (FMCG)",
        "market_cap_category": "Large Cap",
        "nse_ticker": "TITAN.NS",
        "bse_ticker": "500114.BO",
        "base_price": 3760.00,
        "base_pe": 94.0,
        "base_market_cap_cr": 334000,
        "base_52w_high": 3886.95,
        "base_52w_low": 3055.65,
        "dividend_yield": 0.30,
    },
    {
        "symbol": "ADANIENT",
        "name": "Adani Enterprises Ltd",
        "sector": "Metals & Mining",
        "market_cap_category": "Large Cap",
        "nse_ticker": "ADANIENT.NS",
        "bse_ticker": "512599.BO",
        "base_price": 3150.00,
        "base_pe": 88.2,
        "base_market_cap_cr": 359000,
        "base_52w_high": 3743.00,
        "base_52w_low": 2142.00,
        "dividend_yield": 0.05,
    },
    {
        "symbol": "COALINDIA",
        "name": "Coal India Ltd",
        "sector": "Energy & Power",
        "market_cap_category": "Large Cap",
        "nse_ticker": "COALINDIA.NS",
        "bse_ticker": "533278.BO",
        "base_price": 508.00,
        "base_pe": 8.3,
        "base_market_cap_cr": 313000,
        "base_52w_high": 543.55,
        "base_52w_low": 277.50,
        "dividend_yield": 5.05,
    },
    {
        "symbol": "POWERGRID",
        "name": "Power Grid Corporation of India",
        "sector": "Energy & Power",
        "market_cap_category": "Large Cap",
        "nse_ticker": "POWERGRID.NS",
        "bse_ticker": "532898.BO",
        "base_price": 350.00,
        "base_pe": 19.5,
        "base_market_cap_cr": 325000,
        "base_52w_high": 366.25,
        "base_52w_low": 185.00,
        "dividend_yield": 3.20,
    },
    {
        "symbol": "TRENT",
        "name": "Trent Ltd",
        "sector": "Consumer Goods (FMCG)",
        "market_cap_category": "Large Cap",
        "nse_ticker": "TRENT.NS",
        "bse_ticker": "500251.BO",
        "base_price": 7680.00,
        "base_pe": 160.0,
        "base_market_cap_cr": 272000,
        "base_52w_high": 8345.00,
        "base_52w_low": 1945.00,
        "dividend_yield": 0.04,
    },
    {
        "symbol": "BEL",
        "name": "Bharat Electronics Ltd",
        "sector": "Defense & Aerospace",
        "market_cap_category": "Large Cap",
        "nse_ticker": "BEL.NS",
        "bse_ticker": "500049.BO",
        "base_price": 298.50,
        "base_pe": 49.5,
        "base_market_cap_cr": 218000,
        "base_52w_high": 340.50,
        "base_52w_low": 128.00,
        "dividend_yield": 0.75,
    },
    {
        "symbol": "HAL",
        "name": "Hindustan Aeronautics Ltd",
        "sector": "Defense & Aerospace",
        "market_cap_category": "Large Cap",
        "nse_ticker": "HAL.NS",
        "bse_ticker": "541154.BO",
        "base_price": 4480.00,
        "base_pe": 38.2,
        "base_market_cap_cr": 299000,
        "base_52w_high": 5675.00,
        "base_52w_low": 1885.00,
        "dividend_yield": 0.85,
    },
    {
        "symbol": "WIPRO",
        "name": "Wipro Ltd",
        "sector": "Information Technology",
        "market_cap_category": "Large Cap",
        "nse_ticker": "WIPRO.NS",
        "bse_ticker": "507685.BO",
        "base_price": 156.79,
        "base_pe": 22.4,
        "base_market_cap_cr": 164000,
        "base_52w_high": 178.00,
        "base_52w_low": 120.00,
        "dividend_yield": 1.25,
    },
    {
        "symbol": "JIOFIN",
        "name": "Jio Financial Services Ltd",
        "sector": "Banking & Financials",
        "market_cap_category": "Large Cap",
        "nse_ticker": "JIOFIN.NS",
        "bse_ticker": "543940.BO",
        "base_price": 348.00,
        "base_pe": 135.0,
        "base_market_cap_cr": 221000,
        "base_52w_high": 394.70,
        "base_52w_low": 204.65,
        "dividend_yield": 0.0,
    },
    {
        "symbol": "TATAPOWER",
        "name": "Tata Power Company Ltd",
        "sector": "Energy & Power",
        "market_cap_category": "Large Cap",
        "nse_ticker": "TATAPOWER.NS",
        "bse_ticker": "500400.BO",
        "base_price": 455.00,
        "base_pe": 35.8,
        "base_market_cap_cr": 145000,
        "base_52w_high": 494.85,
        "base_52w_low": 235.00,
        "dividend_yield": 0.45,
    },
    {
        "symbol": "VEDL",
        "name": "Vedanta Ltd",
        "sector": "Metals & Mining",
        "market_cap_category": "Mid Cap",
        "nse_ticker": "VEDL.NS",
        "bse_ticker": "500295.BO",
        "base_price": 502.00,
        "base_pe": 14.5,
        "base_market_cap_cr": 186000,
        "base_52w_high": 526.90,
        "base_52w_low": 207.85,
        "dividend_yield": 6.80,
    },
    {
        "symbol": "SUZLON",
        "name": "Suzlon Energy Ltd",
        "sector": "Energy & Power",
        "market_cap_category": "Mid Cap",
        "nse_ticker": "SUZLON.NS",
        "bse_ticker": "532667.BO",
        "base_price": 82.50,
        "base_pe": 85.0,
        "base_market_cap_cr": 112000,
        "base_52w_high": 86.04,
        "base_52w_low": 24.20,
        "dividend_yield": 0.0,
    },
    {
        "symbol": "IRFC",
        "name": "Indian Railway Finance Corp Ltd",
        "sector": "Banking & Financials",
        "market_cap_category": "Large Cap",
        "nse_ticker": "IRFC.NS",
        "bse_ticker": "543257.BO",
        "base_price": 162.00,
        "base_pe": 31.0,
        "base_market_cap_cr": 211000,
        "base_52w_high": 229.00,
        "base_52w_low": 65.50,
        "dividend_yield": 1.10,
    },
    {
        "symbol": "PFC",
        "name": "Power Finance Corporation Ltd",
        "sector": "Banking & Financials",
        "market_cap_category": "Mid Cap",
        "nse_ticker": "PFC.NS",
        "bse_ticker": "532810.BO",
        "base_price": 510.00,
        "base_pe": 8.1,
        "base_market_cap_cr": 168000,
        "base_52w_high": 580.50,
        "base_52w_low": 218.00,
        "dividend_yield": 2.80,
    },
    {
        "symbol": "BHEL",
        "name": "Bharat Heavy Electricals Ltd",
        "sector": "Infrastructure & Capital Goods",
        "market_cap_category": "Mid Cap",
        "nse_ticker": "BHEL.NS",
        "bse_ticker": "500103.BO",
        "base_price": 285.00,
        "base_pe": 140.0,
        "base_market_cap_cr": 99000,
        "base_52w_high": 335.40,
        "base_52w_low": 119.50,
        "dividend_yield": 0.10,
    },
    {
        "symbol": "CDSL",
        "name": "Central Depository Services Ltd",
        "sector": "Banking & Financials",
        "market_cap_category": "Mid Cap",
        "nse_ticker": "CDSL.NS",
        "bse_ticker": "542936.BO",
        "base_price": 1540.00,
        "base_pe": 54.0,
        "base_market_cap_cr": 32000,
        "base_52w_high": 1690.00,
        "base_52w_low": 605.00,
        "dividend_yield": 1.40,
    },
    {
        "symbol": "POLYCAB",
        "name": "Polycab India Ltd",
        "sector": "Infrastructure & Capital Goods",
        "market_cap_category": "Mid Cap",
        "nse_ticker": "POLYCAB.NS",
        "bse_ticker": "542652.BO",
        "base_price": 7180.00,
        "base_pe": 56.0,
        "base_market_cap_cr": 108000,
        "base_52w_high": 7320.00,
        "base_52w_low": 3770.00,
        "dividend_yield": 0.40,
    },
    {
        "symbol": "DIXON",
        "name": "Dixon Technologies (India) Ltd",
        "sector": "Information Technology",
        "market_cap_category": "Mid Cap",
        "nse_ticker": "DIXON.NS",
        "bse_ticker": "540699.BO",
        "base_price": 13950.00,
        "base_pe": 118.0,
        "base_market_cap_cr": 83000,
        "base_52w_high": 15100.00,
        "base_52w_low": 4800.00,
        "dividend_yield": 0.05,
    },
    {
        "symbol": "MAZDOCK",
        "name": "Mazagon Dock Shipbuilders Ltd",
        "sector": "Defense & Aerospace",
        "market_cap_category": "Mid Cap",
        "nse_ticker": "MAZDOCK.NS",
        "bse_ticker": "543237.BO",
        "base_price": 4350.00,
        "base_pe": 44.5,
        "base_market_cap_cr": 88000,
        "base_52w_high": 5860.00,
        "base_52w_low": 1820.00,
        "dividend_yield": 0.55,
    },
    {
        "symbol": "PERSISTENT",
        "name": "Persistent Systems Ltd",
        "sector": "Information Technology",
        "market_cap_category": "Mid Cap",
        "nse_ticker": "PERSISTENT.NS",
        "bse_ticker": "533218.BO",
        "base_price": 5480.00,
        "base_pe": 62.0,
        "base_market_cap_cr": 84500,
        "base_52w_high": 5790.00,
        "base_52w_low": 3200.00,
        "dividend_yield": 0.50,
    },
    {
        "symbol": "KALYANKJIL",
        "name": "Kalyan Jewellers India Ltd",
        "sector": "Consumer Goods (FMCG)",
        "market_cap_category": "Mid Cap",
        "nse_ticker": "KALYANKJIL.NS",
        "bse_ticker": "543278.BO",
        "base_price": 715.00,
        "base_pe": 82.0,
        "base_market_cap_cr": 73600,
        "base_52w_high": 750.00,
        "base_52w_low": 215.00,
        "dividend_yield": 0.15,
    },
    {
        "symbol": "TATAELXSI",
        "name": "Tata Elxsi Ltd",
        "sector": "Information Technology",
        "market_cap_category": "Mid Cap",
        "nse_ticker": "TATAELXSI.NS",
        "bse_ticker": "500408.BO",
        "base_price": 7720.00,
        "base_pe": 57.0,
        "base_market_cap_cr": 48100,
        "base_52w_high": 9200.00,
        "base_52w_low": 6410.00,
        "dividend_yield": 0.90,
    }
]

MARKET_INDICES = [
    {
        "symbol": "NIFTY 50",
        "name": "Nifty 50 Index",
        "ticker": "^NSEI",
        "base_value": 22716.20,
        "exchange": "NSE",
    },
    {
        "symbol": "SENSEX",
        "name": "BSE Sensex 30",
        "ticker": "^BSESN",
        "base_value": 72654.69,
        "exchange": "BSE",
    },
    {
        "symbol": "BANK NIFTY",
        "name": "Nifty Bank Index",
        "ticker": "^NSEBANK",
        "base_value": 54259.95,
        "exchange": "NSE",
    },
    {
        "symbol": "NIFTY IT",
        "name": "Nifty IT Sector Index",
        "ticker": "^CNXIT",
        "base_value": 27670.00,
        "exchange": "NSE",
    },
    {
        "symbol": "INDIA VIX",
        "name": "Volatility Index",
        "ticker": "^INDIAVIX",
        "base_value": 13.37,
        "exchange": "NSE",
    },
]
